exports.countryNameMap = {
  China: 'CN',
  UK: 'GB',
  Martinique: 'MQ',
  Liechtenstein: 'LI',
  'Réunion': 'RE',
  Ukraine: 'UA',
  Honduras: 'HN',
  Afghanistan: 'AF',
  Bangladesh: 'BD',
  Macao: 'MO',
  Bolivia: 'BO',
  Cuba: 'CU',
  Netherlands: 'NL',
  Jamaica: 'JM',
  'French Guiana': 'GF',
  DRC: 'CD',
  Cameroon: 'CM',
  Maldives: 'MV',
  Montenegro: 'ME',
  Paraguay: 'PY',
  Nigeria: 'NG',
  Guam: 'GU',
  'French Polynesia': 'PF',
  Austria: 'AT',
  Ghana: 'GH',
  Rwanda: 'RW',
  Monaco: 'MC',
  Gibraltar: 'GI',
  Guatemala: 'GT',
  'Ivory Coast': 'CI',
  Ethiopia: 'ET',
  Togo: 'TG',
  'Trinidad and Tobago': 'TT',
  Kenya: 'KE',
  Belgium: 'BE',
  Mauritius: 'MU',
  'Equatorial Guinea': 'GQ',
  Kyrgyzstan: 'KG',
  Mongolia: 'MN',
  'Puerto Rico': 'PR',
  Seychelles: 'SC',
  Tanzania: 'TZ',
  Guyana: 'GY',
  Aruba: 'AW',
  Barbados: 'BB',
  Norway: 'NO',
  Mayotte: 'YT',
  'Cayman Islands': 'KY',
  'Curaçao': 'CW',
  Bahamas: 'BS',
  Congo: 'CD',
  Gabon: 'GA',
  Namibia: 'NA',
  'St. Barth': 'BL',
  'Saint Martin': 'MF',
  'U.S. Virgin Islands': 'VI',
  Sweden: 'SE',
  Sudan: 'SD',
  Benin: 'BJ',
  Bermuda: 'BM',
  Bhutan: 'BT',
  CAR: 'CF',
  Greenland: 'GL',
  Haiti: 'HT',
  Liberia: 'LR',
  Mauritania: 'MR',
  'New Caledonia': 'NC',
  Denmark: 'DK',
  'Saint Lucia': 'LC',
  Zambia: 'ZM',
  Nepal: 'NP',
  Angola: 'AO',
  'Antigua and Barbuda': 'AG',
  'Cabo Verde': 'CV',
  Chad: 'TD',
  Djibouti: 'DJ',
  'El Salvador': 'SV',
  Fiji: 'FJ',
  Japan: 'JP',
  Gambia: 'GM',
  Guinea: 'GN',
  'Vatican City': 'VA',
  'Isle of Man': 'IM',
  Montserrat: 'MS',
  Nicaragua: 'NI',
  Niger: 'NE',
  'St. Vincent Grenadines': 'VC',
  'Sint Maarten': 'SX',
  Somalia: 'SO',
  Malaysia: 'MY',
  Suriname: 'SR',
  Eswatini: 'SZ',
  Australia: 'AU',
  Italy: 'IT',
  Canada: 'CA',
  Portugal: 'PT',
  Czechia: 'CZ',
  Israel: 'IL',
  Brazil: 'BR',
  Luxembourg: 'LU',
  Ireland: 'IE',
  Greece: 'GR',
  Qatar: 'QA',
  Pakistan: 'PK',
  Iran: 'IR',
  Finland: 'FI',
  Poland: 'PL',
  Turkey: 'TR',
  Singapore: 'SG',
  Chile: 'CL',
  Iceland: 'IS',
  Thailand: 'TH',
  Slovenia: 'SI',
  Indonesia: 'ID',
  Bahrain: 'BH',
  Spain: 'ES',
  Romania: 'RO',
  'Saudi Arabia': 'SA',
  Estonia: 'EE',
  Ecuador: 'EC',
  Egypt: 'EG',
  Peru: 'PE',
  Philippines: 'PH',
  'Hong Kong': 'HK',
  India: 'IN',
  Russia: 'RU',
  Germany: 'DE',
  Iraq: 'IQ',
  Mexico: 'MX',
  Lebanon: 'LB',
  'South Africa': 'ZA',
  Kuwait: 'KW',
  'San Marino': 'SM',
  UAE: 'AE',
  Panama: 'PA',
  Armenia: 'AM',
  Taiwan: 'TW',
  USA: 'US',
  Argentina: 'AR',
  Colombia: 'CO',
  Slovakia: 'SK',
  Serbia: 'RS',
  Croatia: 'HR',
  Bulgaria: 'BG',
  Uruguay: 'UY',
  Algeria: 'DZ',
  'Costa Rica': 'CR',
  Latvia: 'LV',
  France: 'FR',
  Hungary: 'HU',
  Vietnam: 'VN',
  'Faeroe Islands': 'FO',
  Andorra: 'AD',
  Brunei: 'BN',
  Belarus: 'BY',
  Jordan: 'JO',
  Cyprus: 'CY',
  'Sri Lanka': 'LK',
  Albania: 'AL',
  'S. Korea': 'KR',
  'Bosnia and Herzegovina': 'BA',
  Morocco: 'MA',
  Malta: 'MT',
  'North Macedonia': 'MK',
  Moldova: 'MD',
  Kazakhstan: 'KZ',
  Lithuania: 'LT',
  Oman: 'OM',
  Cambodia: 'KH',
  Palestine: 'PS',
  Switzerland: 'CH',
  Guadeloupe: 'GP',
  Azerbaijan: 'AZ',
  Georgia: 'GE',
  Venezuela: 'VE',
  Tunisia: 'TN',
  'New Zealand': 'NZ',
  Senegal: 'SN',
  'Dominican Republic': 'DO',
  'Burkina Faso': 'BF',
  Uzbekistan: 'UZ',
};